apiVersion: v1
kind: Service
metadata:
  name: blue-green-deployment
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: myapp
    version: v1 # Set to v2 when all the test are passed to send trafic to new version. 