apiVersion: apps/v1
kind: Deployment 
metadata:
  name: myapp-deployment
  labels:
    app: nginx
    version: v1
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
        version: v1
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: v1