apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity: 
      requiredDuringSchedulingIgnoreDuringExecution: # there are two options for this required or preferred 
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In
            values:
            - Large