apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    env: production
    type: front-end
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 8080
#First  way to get values from all configs for this container
    envFrom:
      - configMapRef:
          name: app-config
# Second way to get values for specific configs 
    # env:
    #   - name: APP_COLOR
    #     valueFrom:
    #       configMapKeyRef:
    #         name: app-config
    #         key: APP_COLOR
