# For jobs you can execute one task and after complete the task all pods are terminated  
apiVersion: batch/v1
kind: Job
metadata: 
  name: math-add-job
spec:
  completions: 3 # Number of pod to create to execute the job 
  parallelism: 3 # Number of pod to create at the same time 
  template: 
    spec: 
      containers:
        - name: math-add
          image: ubuntu
          command: ['expr' , '3' ,'+', '4']
      restarPolicy: Never