apiVersion: apps/v1
kind: Deployment 
metadata:
  name: myapp-deployment
  labels:
    app: nginx
    version: v2
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        app: frontend
        version: v2
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 1
  selector:
    matchLabels:
      app: frontend