# Using resources limit for pods 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels: 
    name: postgres-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: demo-voting-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: demo-voting-app
    spec:
      containers:
        - name: postgres
          image: postgres
          resources:
            requests:
              memory: "128Mi"  # Request 128MB of memory
              cpu: "100m"      # Request 0.1 CPU core
            limits:
              memory: "154Mi"  # Limit memory usage to 128MB + 20%
              cpu: "120m"      # Limit CPU usage to 0.1 CPU core + 20%
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
